public class abc_first_2{
    public void myMet()
    {
        System.debug('Heyyyyyyyyyyyyy ! Aakash How are you 2');
        System.debug('Heyyyyyyyyyyyyy ! Aakash How are you 2');
        System.debug('Heyyyyyyyyyyyyy ! Aakash How are you 2');
        System.debug('Heyyyyyyyyyyyyy ! Aakash How are you 2');
        System.debug('Heyyyyyyyyyyyyy ! Aakash How are you 2');
        System.debug('Heyyyyyyyyyyyyy ! Aakash How are you 2');
        System.debug('Heyyyyyyyyyyyyy ! Aakash How are you 2');
        System.debug('Heyyyyyyyyyyyyy ! Aakash How are you 2');
        System.debug('Heyyyyyyyyyyyyy ! Aakash How are you 2');
        System.debug('Heyyyyyyyyyyyyy ! Aakash How are you 2');
        System.debug('Ok We have successfully pulled one file from Remote through Plugins.............');
        System.debug('Ok We have successfully pulled one file from Remote through Plugins.............');
    }
}
